version: '3.9'
services:

  newsfeed:
    image: alexwoolford/supply-chain-newsfeed:1.0.3
    container_name: supply-chain-newsfeed
    restart: unless-stopped
    hostname: newsfeed
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: pkc-lzvrd.us-west4.gcp.confluent.cloud:9092
      SPRING_KAFKA_SECURITY_PROTOCOL: SASL_SSL
      SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule   required username="********"   password="********";
      SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: PLAIN
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
      RSS_FEED_URLS[0]: https://rss.app/feeds/a74t9VrimjtL7Mzl.xml
      RSS_FEED_URLS[1]: https://feeds.feedburner.com/sc247/rss/supplychain247
      RSS_FEED_URLS[2]: https://rss.app/feeds/L8Unydalin1riPwM.xml
      RSS_FEED_URLS[3]: https://www.supplychaindive.com/feeds/news/
      AWS_ACCESS_KEY_ID: XXXXXXXX
      AWS_SECRET_ACCESS_KEY: XXXXXXXX
